name: '@csv-stream/lib'

on:
  push:
    branches: [main]
    paths:
      - 'packages/csv-stream-lib/**'
      - '.github/workflows/csv-stream-lib.yml'
  pull_request:
    paths:
      - 'packages/csv-stream-lib/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 17.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Test
        run: npm run test -w @csv-stream/lib
